"""Poetic English paraphrases for Starbucks 啡快 passphrase corpus (sb_1–sb_304)."""

TRANSLATIONS: dict[str, str] = {
    "sb_1": "Lucky koi, today",
    "sb_2": "Artsy soul",
    "sb_3": "All's well enough",
    "sb_4": "Little angel",
    "sb_5": "Skills never hurt",
    "sb_6": "Koi incarnate",
    "sb_7": "Light on water",
    "sb_8": "Radiant charm",
    "sb_9": "So brilliant",
    "sb_10": "Birdsong, cicada hum",
    "sb_11": "That golden child",
    "sb_12": "Sudden joy",
    "sb_13": "Summer's favorite",
    "sb_14": "A cup to moonlight",
    "sb_15": "Spider-Man",
    "sb_16": "Open sesame",
    "sb_17": "Dragon-slaying blade",
    "sb_18": "Moonlight box",
    "sb_19": "The neighbor's wonder",
    "sb_20": "Azure sea",
    "sb_21": "Go dive",
    "sb_22": "Everything grows",
    "sb_23": "Water park dreams",
    "sb_24": "Six-vein sword",
    "sb_25": "Speed wins all",
    "sb_26": "He summered summer",
    "sb_27": "I Am Spider-Man",
    "sb_28": "In autumn's name",
    "sb_29": "Clouds disperse",
    "sb_30": "Sweet journey",
    "sb_31": "Worries scatter",
    "sb_32": "The world still holds you",
    "sb_33": "Let's go!",
    "sb_34": "Nice, so nice",
    "sb_35": "Draw a dragon, left",
    "sb_36": "Northern doodler",
    "sb_37": "Reboot and try",
    "sb_38": "Stars and sea together",
    "sb_39": "Spring at its best",
    "sb_40": "Sunny year ahead",
    "sb_41": "Winter sun warmth",
    "sb_42": "Autumn moon, bright night",
    "sb_43": "Warm drinks, autumn starts",
    "sb_44": "Most special one",
    "sb_45": "Beauty takes the stage",
    "sb_46": "Bump cups with joy",
    "sb_47": "Warm sun for you",
    "sb_48": "Warmth on tap",
    "sb_49": "Peace and quiet joy",
    "sb_50": "Fortune at the door",
    "sb_51": "Joy every year",
    "sb_52": "Winning years ahead",
    "sb_53": "Rich, lean, cool",
    "sb_54": "Long pole, wide bench",
    "sb_55": "Coral sea",
    "sb_56": "Rainbow, right hand",
    "sb_57": "White beard incoming",
    "sb_58": "Laugh with power",
    "sb_59": "Coolest one around",
    "sb_60": "Hi, I'm off",
    "sb_61": "Favorite season: fall",
    "sb_62": "Koi in moonlight",
    "sb_63": "Let's go!",
    "sb_64": "Chosen one",
    "sb_65": "Little prodigy",
    "sb_66": "Tossed bowl noodles",
    "sb_67": "Go go duck!",
    "sb_68": "All things auspicious",
    "sb_69": "Mercury, step aside",
    "sb_70": "Summer of joy",
    "sb_71": "Power granted you",
    "sb_72": "Summon the dragon",
    "sb_73": "Americano happens",
    "sb_74": "Friends await ahead",
    "sb_75": "Travel inward",
    "sb_76": "Romance unending",
    "sb_77": "Grace still on its way",
    "sb_78": "Fresh year, fresh spark",
    "sb_79": "Clear wind, bright scene",
    "sb_80": "May, full of hope",
    "sb_81": "Dads on fire",
    "sb_82": "Smooth travels",
    "sb_83": "Quietly dazzling all",
    "sb_84": "Luck tank full",
    "sb_85": "Dobby is free",
    "sb_86": "Hogwarts welcomes you",
    "sb_87": "Grip your wand",
    "sb_88": "Victory in time",
    "sb_89": "Azure dragon, white tiger",
    "sb_90": "Through Platform 9¾",
    "sb_91": "Freedom, final magic",
    "sb_92": "Ever joyful, ever calm",
    "sb_93": "Grow upward",
    "sb_94": "Triple thumbs-up today",
    "sb_95": "All in season",
    "sb_96": "Fierce and sincere",
    "sb_97": "Forever in bloom",
    "sb_98": "Happiness doubled",
    "sb_99": "New year, heart's desire",
    "sb_100": "Frost for you",
    "sb_101": "Spring opens red-hot",
    "sb_102": "All flows smooth",
    "sb_103": "Take it easy.",
    "sb_104": "Be real.",
    "sb_105": "Good vibes.",
    "sb_106": "Dare to dream.",
    "sb_107": "Every effort, whole heart",
    "sb_108": "May tomorrow outshine yesterday",
    "sb_109": "For love, take the field",
    "sb_110": "Dawn waits ahead",
    "sb_111": "Heavy with fruit",
    "sb_112": "Let the smile come",
    "sb_113": "Haste softens into roundness",
    "sb_114": "Run toward joy",
    "sb_115": "Bloom where rooted",
    "sb_116": "Turn in good time",
    "sb_117": "Far places shine",
    "sb_118": "Worry-dissolving spell",
    "sb_119": "No need to pose strong",
    "sb_120": "Cherish it all",
    "sb_121": "As you are, enough",
    "sb_122": "Breeze reads for me",
    "sb_123": "Wide heart, wide road",
    "sb_124": "Sky high, birds roam",
    "sb_125": "What matters: leaving",
    "sb_126": "Your own rose",
    "sb_127": "Best version, you",
    "sb_128": "Meeting beats all",
    "sb_129": "New chapter",
    "sb_130": "Meet today",
    "sb_131": "Easy and free",
    "sb_132": "Blissfully laid-back",
    "sb_133": "Scenic road, verse road",
    "sb_134": "Workers, all who come",
    "sb_135": "Steady gait",
    "sb_136": "Sunward all the way",
    "sb_137": "No regrets left",
    "sb_138": "Much to accomplish",
    "sb_139": "Footprints behind",
    "sb_140": "Freedom in the wind",
    "sb_141": "Fierce and free",
    "sb_142": "Smooth every path",
    "sb_143": "Beauty stays near",
    "sb_144": "Fun, hope, no frets",
    "sb_145": "All as wished",
    "sb_146": "Praise yourself aloud",
    "sb_147": "Walk with distinction",
    "sb_148": "Mind, crystal clear",
    "sb_149": "May paths be runnable",
    "sb_150": "Love street-life glow",
    "sb_151": "Never drop offline",
    "sb_152": "Life grows toward beauty",
    "sb_153": "Wishes thought, granted",
    "sb_154": "Verse and far horizons",
    "sb_155": "Victorious wherever",
    "sb_156": "Highlight mode on",
    "sb_157": "Someone's always young",
    "sb_158": "Each moment, possibility",
    "sb_159": "Content, unshaken",
    "sb_160": "Trying looks cool",
    "sb_161": "Joy remembered, not sorrow",
    "sb_162": "Summer tapped your shoulder",
    "sb_163": "Heart's wish, fulfilled",
    "sb_164": "Birdsong, floral air",
    "sb_165": "Dawn ahead on the road",
    "sb_166": "Laughter, hardship's cure",
    "sb_167": "Don't miss sky's rainbow",
    "sb_168": "Savor the whole world",
    "sb_169": "Wade thousand waves",
    "sb_170": "Results not required",
    "sb_171": "Heart moves by you",
    "sb_172": "Leave no what-ifs",
    "sb_173": "All things warm and bright",
    "sb_174": "Love beyond this moment",
    "sb_175": "Heart toward wild plains",
    "sb_176": "Just enough, just right",
    "sb_177": "Coffee, wind in hair",
    "sb_178": "Anything might happen",
    "sb_179": "Flowers face the sun",
    "sb_180": "All things lucid",
    "sb_181": "Look up, catch luck",
    "sb_182": "Flow, joy, peace",
    "sb_183": "New story awaited",
    "sb_184": "Today's finest",
    "sb_185": "Leave the day unwritten",
    "sb_186": "Busy bounded, leisure lit",
    "sb_187": "Where the wind lives",
    "sb_188": "Almost full beats perfect",
    "sb_189": "Good thing, right time",
    "sb_190": "Roses owed to you",
    "sb_191": "Always beside you",
    "sb_192": "Come to the feast magical",
    "sb_193": "Hogwarts never graduates",
    "sb_194": "Wrapped in gifts",
    "sb_195": "Slow down, see world",
    "sb_196": "Spring en route",
    "sb_197": "You are scenery too",
    "sb_198": "Dawn up ahead",
    "sb_199": "Fresh starting line",
    "sb_200": "Home, only castle",
    "sb_201": "Hand in hand",
    "sb_202": "Sweetness in memory",
    "sb_203": "Clear skies all through",
    "sb_204": "Passion, life's antidote",
    "sb_205": "Unhurried heart, quiet knowing",
    "sb_206": "Long road, still glittering",
    "sb_207": "Luck unstoppable",
    "sb_208": "Carefree, unafraid",
    "sb_209": "Eyes forward",
    "sb_210": "Good mood sprouting",
    "sb_211": "Magic adventure",
    "sb_212": "Infuse full vitality",
    "sb_213": "Light-chasers glow",
    "sb_214": "You, bold and open",
    "sb_215": "Life, infinite maybe",
    "sb_216": "Keep the leaving mood",
    "sb_217": "Beauty arrives unplanned",
    "sb_218": "Heartbeat to motion",
    "sb_219": "Moon lights hills and rivers",
    "sb_220": "Tomorrow beats yesterday",
    "sb_221": "A cosmos of your own",
    "sb_222": "New year, more self-love",
    "sb_223": "Stars don't ask who's rushing",
    "sb_224": "Live this now",
    "sb_225": "Sorting in progress",
    "sb_226": "Days we glow together",
    "sb_227": "At peace with all things",
    "sb_228": "Hands held, world's end",
    "sb_229": "Fall for Mayday",
    "sb_230": "Sing with force",
    "sb_231": "Mayday midsummer",
    "sb_232": "Hold you tight",
    "sb_233": "I'm not the same",
    "sb_234": "Never let go",
    "sb_235": "Love is treasure",
    "sb_236": "Run wild, love hard",
    "sb_237": "Lose some, gain some",
    "sb_238": "This moment, pure",
    "sb_239": "Drop the worries",
    "sb_240": "Enough, right now",
    "sb_241": "Walk on together",
    "sb_242": "Pinky promise",
    "sb_243": "Fly against wind",
    "sb_244": "Catch the summer",
    "sb_245": "Good day to meet",
    "sb_246": "Answers still en route",
    "sb_247": "Good news, buffering",
    "sb_248": "When still, feel breeze",
    "sb_249": "Fill joy to brim",
    "sb_250": "Bright every day",
    "sb_251": "Let all unfold",
    "sb_252": "Wishes come true",
    "sb_253": "This cup to rainbow",
    "sb_254": "Cutest rank one",
    "sb_255": "Peach scent, fresh bloom",
    "sb_256": "Family in health",
    "sb_257": "New year, charge upward",
    "sb_258": "Toward joy, depart",
    "sb_259": "Coffee freedom",
    "sb_260": "A bit bunny-ish",
    "sb_261": "All luck to you",
    "sb_262": "Ten of ten perfect",
    "sb_263": "Peace, apple-blessed",
    "sb_264": "Dreams within reach",
    "sb_265": "Listen inside",
    "sb_266": "Always a far place to go",
    "sb_267": "Brows unfurrowed",
    "sb_268": "Heart-led, free-spirited",
    "sb_269": "Walk on, don't betray road",
    "sb_270": "Happy being you",
    "sb_271": "Drive and direction",
    "sb_272": "Earn your depth",
    "sb_273": "New year, sudden wealth",
    "sb_274": "Beauty still inbound",
    "sb_275": "Passion long-burning",
    "sb_276": "From today, restart",
    "sb_277": "Time shallow-clear",
    "sb_278": "Bright days rushing in",
    "sb_279": "All wished-for, real",
    "sb_280": "Chase dreams in shade",
    "sb_281": "Clouds roam free too",
    "sb_282": "Far shores self-brighten",
    "sb_283": "Steps follow heart",
    "sb_284": "All things can wait hopefully",
    "sb_285": "Struggle up, meet at peak",
    "sb_286": "Head high, look on",
    "sb_287": "You'll meet naturally",
    "sb_288": "Filter the frets",
    "sb_289": "Keep curiosity alive",
    "sb_290": "Wind moves, heart too",
    "sb_291": "Mood sunlit",
    "sb_292": "Walk the dream line",
    "sb_293": "Beauty meets by chance",
    "sb_294": "Ten thousand things renew",
    "sb_295": "Luck without limit",
    "sb_296": "Empty out completely",
    "sb_297": "Worth the jotting down",
    "sb_298": "All wants received",
    "sb_299": "Nothing out of reach",
    "sb_300": "Slowly understood",
    "sb_301": "Gains, losses lightly held",
    "sb_302": "Stay curious",
    "sb_303": "Heaven has its say",
    "sb_304": "New achievement unlocked",
}

if __name__ == "__main__":
    import json
    from pathlib import Path

    out = Path(__file__).parent / "phrases_en.json"
    out.write_text(json.dumps(TRANSLATIONS, ensure_ascii=False, indent=2) + "\n")
